services:
  infinity:
    image: michaelf34/infinity:0.0.70-cpu
    container_name: jamai_infinity
    command: ["v2", "--engine", "torch", "--port", "6909", "--model-warmup", "--model-id", "${EMBEDDING_MODEL}", "--model-id", "${RERANKER_MODEL}"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:6909/health"]
      interval: 10s
      timeout: 2s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ${PWD}/docker_data/infinity_cache:/app/.cache
    networks:
      - jamai
